---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE, tidy = TRUE)
```

<br><br>

# Selected R Packages

```{r showcase, echo = FALSE}
library(shiny)
library(apputils)
pkgs <- c("epubr", "mapmate", "memery", "rockchain", "rtrek", "rvtable", "tabr", "tiler", "trekfont")
page_urls <- paste0("https://leonawicz.github.io/", pkgs)
page_urls[pkgs == "trekfont"] <- "https://github.com/leonawicz/trekfont"
img_urls <- paste0("https://github.com/leonawicz/", pkgs, "/blob/master/data-raw/", 
                   ifelse(pkgs == "rtrek", "images/rtrek", pkgs), ".png?raw=true")
gh_urls <- paste0("https://github.com/leonawicz/", pkgs)
lab <- paste0("<h4>", pkgs,
  "<a href=\"", gh_urls, "\" style=\"padding-left:10px;\"><span class=\"fa fa-github fa-lg\"></span></a></h4>")
lab <- purrr::map(lab, ~HTML(.x))
subtitles <- c("Tidy EPUB data", "Globe animation", "For data nerds", "Blockchain in R", 
               "All things Star Trek", "Density frames", "Guitar tabs", "Star Trek fonts")
app_showcase(page_urls, img_urls, pkgs, subtitles, lab, min_width = 150, max_width = 150, img_style = "padding:5px;", new_window = FALSE)
```
