---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE, tidy = TRUE)
```

<br><br>

# Projects

```{r showcase, echo = FALSE}
library(shiny)
library(apputils)
page_urls <- paste0(
  "https://leonawicz.github.io/", 
  c("CommCharts4", "DataExtraction", "Downscaling", "Flammability", "LandCarbon", "SNAPQAQC"))
img_urls <- paste0(
  "https://github.com/leonawicz/",
  c("CommCharts4/raw/master/plots/_CommCharts4.png",
  "DataExtraction/raw/master/plots/_DataExtraction.png",
  "Downscaling/raw/master/plots/_Downscaling.jpg",
  "Flammability/raw/master/plots/_Flammability.png",
  "LandCarbon/raw/master/plots/_LandCarbon.png",
  "SNAPQAQC/raw/master/plots/_SNAPQAQC.jpg"))
gh_urls <- paste0(
  "https://github.com/leonawicz/",
  c("CommCharts4", "DataExtraction", "Downscaling", "Flammability", "LandCarbon", "SNAPQAQC"))
labels <- c("Community climate charts", "Data extraction", "Climate downscaling", 
            "Landscape flammability", "Land carbon", "Data quality control")
labs <- paste0("<h4>", labels,
  "<a href=\"", gh_urls, "\" style=\"padding-left:10px;\"><span class=\"fa fa-github fa-lg\"></span></a></h4>")
labs <- purrr::map(labs, ~HTML(.x))
titles <- c("Community charts", "Extractions/estimations", "Climate downscaling",
            "Landscape flammability", "Land carbon outputs", "Assorted QC code")
subtitles <- rep("Project documentation", 6)
app_showcase(page_urls, img_urls, titles, subtitles, labs, new_window = FALSE)
```
